### ISSUE TITLE
x-axis resolution

### ISSUE THREAD

**Issue by helioshk** [darksidelemm/kiwisnr-rrd#3]
Hi,
I would like to generate a spectrum plot in higher temporal resolution, for example with 1 minute per pixel.
Is this possible? How could I do that?
Thanks

**Comment by darksidelemm** [comment]
It the input data has higher resolution, then the plot should be produced with higher resolution too. 
It should be a matter of running the collection script more often.

**Comment by helioshk** [comment]
I have 1 minute update interval and it seems it is about 1.75 minutes per pixel in the spectrum plot.
But it's good enough and looks great, thank you for the scripts.
