### ISSUE TITLE
rx channel selection in 8 channel mode

### ISSUE THREAD

**Issue by helioshk** [darksidelemm/kiwisnr-rrd#4]
Is it possible for kiwisnr to prioritize to which channel it should connect? 
I would like it to connect to the limited channels (audio FFT only) only, in order to not occupy the full waterfall channels. 
I know that kiwirecorder does that somehow, but couldn't figure out how.

Edit: On a second thought, it probably wouldn't work well on the audio only channel.

**Comment by darksidelemm** [comment]
KiwiSNR *requires* a full waterfall, so this wouldn't work?

**Comment by helioshk** [comment]
Yeah that was silly. thanks.
